### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1200384x17 and 18x64)

### ISSUE THREAD

**Issue by zyd98123** [frigategnn/Frigate#4]
First of all, thank you for your excellent work. After reading your paper, I am very interested in your work. However, when I tried to reproduce your code, I encountered the following problem. I am not sure if you have experienced this issue before, but I would be very grateful if you could provide any examples of errors encountered during your work. Below is the error I encountered while running your program:

E:\anaconda\envs\zyd\lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.NeighborSampler' is deprecated, use 'loader.NeighborSampler' instead
  warnings.warn(out)
Traceback (most recent call last):
  File "C:/Users/17131/Desktop/Frigate-main/train.py", line 128, in <module>
    main()
  File "C:/Users/17131/Desktop/Frigate-main/train.py", line 122, in main
    model_train(model_args, device, pargs.nepochs, dataloaders, edge_weight,
  File "C:\Users\17131\Desktop\Frigate-main\model\trainer.py", line 64, in model_train
    train_loss = train_step(model, opt, lr_scheduler, dataloaders['train_loader'], device, logger, loss_fn, e, edge_weight, TFRate)
  File "C:\Users\17131\Desktop\Frigate-main\model\trainer.py", line 114, in train_step
    y_hat = model(x_slice, x_slice_rev, adjs, adjs_rev, edge_weight, lipschitz, y_slice, TFRate=TFRate, mu=mu, std=sig)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\17131\Desktop\Frigate-main\model\model.py", line 191, in forward
    enc_output, mean = this.enc(xs, xrev, adjs, adjs_rev, edge_weight, lipschitz, mu, std)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\17131\Desktop\Frigate-main\model\model.py", line 112, in forward
    hs, xsum, count = this.gnn(xs, adjs, edge_weight, lipschitz, mu, std)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\17131\Desktop\Frigate-main\model\model.py", line 81, in forward
    xs = this.gc[i]((xs, xs_target), edge_index, edge_weight[e_id],
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\17131\Desktop\Frigate-main\model\model.py", line 31, in forward
    x_r = this.lin_r(x[1])
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\anaconda\envs\zyd\lib\site-packages\torch\nn\modules\linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1200384x17 and 18x64)

**Comment by zyd98123** [comment]
I have solved this problem, according to the configuration in the freeze1.txt given by the author, remember that torch-geometric==1.7.2 in it, and my environment is torch2.3.0+cuda12.1, and the torch-geometric==2.3.5 at default pip only needs to be lowered to torch-geometric==1.7.2
